### ISSUE TITLE
apply the BridgeDb main website layout

### ISSUE THREAD

**Issue by egonw** [bridgedb/data#4]
@Chris-Evelo suggested to apply the BridgeDb main website layout.

**Comment by egonw** [comment]
@Chris-Evelo, the current design of the BridgeDb website is a stock design. I don't even think that should look like that. I think it is technically possible to apply that design to this repository too, but that would need testing.

I also like to stress that before x-mas this download page also did not have design of the main BridgeDb website. So, this would really be a new feature.

**Comment by Chris-Evelo** [comment]
I don't care too much what it looks like. But:

1) I think there is some advantage to a consistent design and consistent logic throughout a website. That makes things easier to find on a page, makes you not wonder whether you still are on the website, and in general just looks more professional.
2) The main design has a menu bar. That is of course part of that consistent logic. But this also really helps to find descriptions, citation information and such. Since people really might enter the site on this data page (either because of search engines or because somebody gives that as the link for data used, it would be good if we provide that navigation info.
3) The main design also has some other relevant info, related to being a RIR and such. 

But maybe I miss how complicated this really is? Lauren said she could probably change the format. Would you mind if she does?

**Comment by egonw** [comment]
Yeah, we can do whatever we like. It's just that I cannot really find funding for website layout development...

**Comment by Chris-Evelo** [comment]
I don't think we need to develop a design, we already have one. We just need to apply it to this page.

**Comment by egonw** [comment]
![image](https://user-images.githubusercontent.com/26721/236621465-52890093-af9b-4738-b20e-cc9f75d2fef6.png)
